// Curated sample resumes shown on the homepage. These are illustrative
// only — a signed-in user's own analyses live under /previous and are
// fetched from the backend, never mixed into this list.
export const resumes: Resume[] = [
  {
    id: "sample-1",
    companyName: "Google",
    jobTitle: "Frontend Developer",
    imagePath: "/images/resume_01.png",
    resumePath: "/resumes/resume-1.pdf",
    isSample: true,
    feedback: {
      overallScore: 85,
      ATS: { score: 90, tips: [] },
      toneAndStyle: { score: 90, tips: [] },
      content: { score: 90, tips: [] },
      structure: { score: 90, tips: [] },
      skills: { score: 90, tips: [] },
    },
  },
  {
    id: "sample-2",
    companyName: "Microsoft",
    jobTitle: "Cloud Engineer",
    imagePath: "/images/resume_02.png",
    resumePath: "/resumes/resume-2.pdf",
    isSample: true,
    feedback: {
      overallScore: 55,
      ATS: { score: 90, tips: [] },
      toneAndStyle: { score: 90, tips: [] },
      content: { score: 90, tips: [] },
      structure: { score: 90, tips: [] },
      skills: { score: 90, tips: [] },
    },
  },
  {
    id: "sample-3",
    companyName: "Apple",
    jobTitle: "iOS Developer",
    imagePath: "/images/resume_03.png",
    resumePath: "/resumes/resume-3.pdf",
    isSample: true,
    feedback: {
      overallScore: 75,
      ATS: { score: 90, tips: [] },
      toneAndStyle: { score: 90, tips: [] },
      content: { score: 90, tips: [] },
      structure: { score: 90, tips: [] },
      skills: { score: 90, tips: [] },
    },
  },
  {
    id: "sample-4",
    companyName: "Tesla",
    jobTitle: "Product Designer",
    imagePath: "/images/resume_04.png",
    resumePath: "/resumes/resume-4.pdf",
    isSample: true,
    feedback: {
      overallScore: 68,
      ATS: { score: 82, tips: [] },
      toneAndStyle: { score: 74, tips: [] },
      content: { score: 70, tips: [] },
      structure: { score: 65, tips: [] },
      skills: { score: 68, tips: [] },
    },
  },
  {
    id: "sample-5",
    companyName: "Amazon",
    jobTitle: "Data Analyst",
    imagePath: "/images/resume_05.png",
    resumePath: "/resumes/resume-5.pdf",
    isSample: true,
    feedback: {
      overallScore: 80,
      ATS: { score: 88, tips: [] },
      toneAndStyle: { score: 82, tips: [] },
      content: { score: 79, tips: [] },
      structure: { score: 75, tips: [] },
      skills: { score: 82, tips: [] },
    },
  },
  {
    id: "sample-6",
    companyName: "Netflix",
    jobTitle: "Marketing Manager",
    imagePath: "/images/resume_06.png",
    resumePath: "/resumes/resume-6.pdf",
    isSample: true,
    feedback: {
      overallScore: 72,
      ATS: { score: 80, tips: [] },
      toneAndStyle: { score: 76, tips: [] },
      content: { score: 74, tips: [] },
      structure: { score: 70, tips: [] },
      skills: { score: 72, tips: [] },
    },
  },
];
