import Anthropic from "@anthropic-ai/sdk";

const MODEL = process.env.ANTHROPIC_MODEL || "claude-sonnet-5";

const RESPONSE_SHAPE = `{
  "overallScore": number (0-100),
  "ATS": { "score": number (0-100), "tips": [{ "type": "good"|"improve", "tip": string }] (3-4 items) },
  "toneAndStyle": { "score": number (0-100), "tips": [{ "type": "good"|"improve", "tip": string, "explanation": string }] (3-4 items) },
  "content": { "score": number (0-100), "tips": [{ "type": "good"|"improve", "tip": string, "explanation": string }] (3-4 items) },
  "structure": { "score": number (0-100), "tips": [{ "type": "good"|"improve", "tip": string, "explanation": string }] (3-4 items) },
  "skills": { "score": number (0-100), "tips": [{ "type": "good"|"improve", "tip": string, "explanation": string }] (3-4 items) }
}`;

function buildPrompt({ resumeText, jobTitle, jobDescription }) {
  return `You are an expert in ATS (Applicant Tracking System) and resume analysis.
Analyze and rate the resume below and suggest how to improve it.
Be thorough and honest — give low scores where they are deserved, this is meant to help the candidate improve.
${jobTitle ? `The job title is: ${jobTitle}\n` : ""}${jobDescription ? `The job description is: ${jobDescription}\n` : ""}
Resume text (extracted from the uploaded PDF):
"""
${resumeText.slice(0, 12000)}
"""

Respond with ONLY a raw JSON object (no markdown fences, no commentary) matching exactly this shape:
${RESPONSE_SHAPE}`;
}

function extractJson(raw) {
  try {
    return JSON.parse(raw);
  } catch {
    const match = raw.match(/\{[\s\S]*\}/);
    if (match) return JSON.parse(match[0]);
    throw new Error("Model response was not valid JSON");
  }
}

/**
 * Very small heuristic analyzer used when no ANTHROPIC_API_KEY is
 * configured, so the app is fully demoable out of the box. It is not a
 * replacement for the real model — swap in your key to get genuine
 * AI feedback.
 */
function heuristicFeedback({ resumeText, jobDescription }) {
  const words = resumeText.trim().split(/\s+/).filter(Boolean);
  const wordCount = words.length;
  const hasEmail = /[\w.+-]+@[\w-]+\.[\w.-]+/.test(resumeText);
  const hasPhone = /(\+?\d[\d\s().-]{7,}\d)/.test(resumeText);
  const bulletCount = (resumeText.match(/\n\s*[•\-*]/g) || []).length;

  const jdWords = (jobDescription || "")
    .toLowerCase()
    .split(/[^a-z0-9+#.]+/)
    .filter((w) => w.length > 3);
  const uniqueJdWords = [...new Set(jdWords)].slice(0, 40);
  const resumeLower = resumeText.toLowerCase();
  const matched = uniqueJdWords.filter((w) => resumeLower.includes(w));
  const keywordCoverage = uniqueJdWords.length
    ? matched.length / uniqueJdWords.length
    : 0.6;

  const lengthScore = wordCount < 150 ? 45 : wordCount > 1200 ? 55 : 85;
  const contactScore = (hasEmail ? 50 : 0) + (hasPhone ? 50 : 0);
  const structureScore = bulletCount >= 4 ? 82 : bulletCount >= 1 ? 65 : 45;
  const atsScore = Math.round((lengthScore + contactScore) / 2);
  const skillsScore = Math.round(keywordCoverage * 100);
  const contentScore = Math.round((lengthScore + skillsScore) / 2);
  const overall = Math.round(
    (atsScore + structureScore + contentScore + skillsScore + 75) / 5,
  );

  const tip = (type, tip, explanation) => ({ type, tip, explanation });

  return {
    overallScore: overall,
    ATS: {
      score: atsScore,
      tips: [
        { type: hasEmail && hasPhone ? "good" : "improve", tip: "Contact details" },
        { type: bulletCount > 0 ? "good" : "improve", tip: "Uses bullet points" },
        { type: wordCount > 150 ? "good" : "improve", tip: "Sufficient content length" },
      ],
    },
    toneAndStyle: {
      score: structureScore,
      tips: [
        tip(
          bulletCount >= 4 ? "good" : "improve",
          "Bulleted achievements",
          bulletCount >= 4
            ? "Your resume uses bullet points consistently, which scans well for both humans and ATS parsers."
            : "Consider converting long paragraphs into concise, bulleted achievement statements.",
        ),
        tip(
          "improve",
          "Automated review only",
          "This feedback was generated by a lightweight fallback analyzer because no AI provider key is configured on the backend — set ANTHROPIC_API_KEY for full AI feedback.",
        ),
      ],
    },
    content: {
      score: contentScore,
      tips: [
        tip(
          wordCount > 150 ? "good" : "improve",
          "Resume length",
          `Your resume contains roughly ${wordCount} words. Aim for 400-800 words for most roles.`,
        ),
      ],
    },
    structure: {
      score: structureScore,
      tips: [
        tip(
          bulletCount > 0 ? "good" : "improve",
          "Section structure",
          bulletCount > 0
            ? "Bullet points were detected, which usually indicates clear sectioning."
            : "No bullet points were detected — clear section headers and bullets help both recruiters and ATS software.",
        ),
      ],
    },
    skills: {
      score: skillsScore,
      tips: [
        tip(
          keywordCoverage > 0.4 ? "good" : "improve",
          "Keyword match with job description",
          uniqueJdWords.length
            ? `${matched.length} of ${uniqueJdWords.length} key terms from the job description were found in your resume.`
            : "No job description was provided, so keyword matching was skipped.",
        ),
      ],
    },
  };
}

export async function analyzeResume({ resumeText, jobTitle, jobDescription }) {
  const apiKey = process.env.ANTHROPIC_API_KEY;

  if (!apiKey) {
    return heuristicFeedback({ resumeText, jobDescription });
  }

  const client = new Anthropic({ apiKey });
  const message = await client.messages.create({
    model: MODEL,
    max_tokens: 2000,
    messages: [
      { role: "user", content: buildPrompt({ resumeText, jobTitle, jobDescription }) },
    ],
  });

  const textBlock = message.content.find((block) => block.type === "text");
  if (!textBlock) throw new Error("No text response from the AI model");

  return extractJson(textBlock.text);
}
